// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {system} from '../models';
import {pxe} from '../models';

export function ActivateLicense(arg1:string):Promise<license.ActivateResult>;

export function BrowseISO():Promise<string>;

export function BuildISO(arg1:string,arg2:string,arg3:string):Promise<system.CommandResult>;

export function CheckLicense():Promise<license.Status>;

export function ExtractISO(arg1:string,arg2:string):Promise<system.CommandResult>;

export function GetLicenseInfo():Promise<license.Info>;

export function GetNetworkInterfaces():Promise<Array<system.NetworkInterface>>;

export function GetPXELogs():Promise<Array<string>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GetWorkspaceDir():Promise<string>;

export function InjectDrivers(arg1:string,arg2:string):Promise<system.CommandResult>;

export function IsPXERunning():Promise<boolean>;

export function MountWIM(arg1:string,arg2:string):Promise<system.CommandResult>;

export function StartPXE(arg1:string,arg2:string,arg3:string):Promise<pxe.StartResult>;

export function StopPXE():Promise<void>;

export function UnmountWIM(arg1:string,arg2:boolean):Promise<system.CommandResult>;
