// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function BrowseISO() {
  return window['go']['main']['App']['BrowseISO']();
}

export function BuildISO(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildISO'](arg1, arg2, arg3);
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function ExtractISO(arg1, arg2) {
  return window['go']['main']['App']['ExtractISO'](arg1, arg2);
}

export function GetLicenseInfo() {
  return window['go']['main']['App']['GetLicenseInfo']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetPXELogs() {
  return window['go']['main']['App']['GetPXELogs']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetWorkspaceDir() {
  return window['go']['main']['App']['GetWorkspaceDir']();
}

export function InjectDrivers(arg1, arg2) {
  return window['go']['main']['App']['InjectDrivers'](arg1, arg2);
}

export function IsPXERunning() {
  return window['go']['main']['App']['IsPXERunning']();
}

export function MountWIM(arg1, arg2) {
  return window['go']['main']['App']['MountWIM'](arg1, arg2);
}

export function StartPXE(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPXE'](arg1, arg2, arg3);
}

export function StopPXE() {
  return window['go']['main']['App']['StopPXE']();
}

export function UnmountWIM(arg1, arg2) {
  return window['go']['main']['App']['UnmountWIM'](arg1, arg2);
}
